fixtures:
  repositories:
    stdlib: 
      repo: git://github.com/puppetlabs/puppetlabs-stdlib.git
      ref: "2.3.0"
    file_concat: git://github.com/electrical/puppet-lib-file_concat.git
    apt: git://github.com/puppetlabs/puppetlabs-apt.git
  symlinks:
    logstash: "#{source_dir}"
